# This file was auto-generated by Fern from our API Definition.

import typing

from .access_right import AccessRight

AccessRights = typing.List[AccessRight]
"""
A set of rights. Encoded as distinct names in `read`, `history`, `write`,
`create`, `remove`, `share`, `manage`, `admin` order. Decoding accepts any
order and rejects repeated names.
"""
