# This file was auto-generated by Fern from our API Definition.

AttributeRevisionNo = int
"""
Revision number for an inode's attributes. It starts at 0 and increases whenever the attribute map changes.
"""
