# This file was auto-generated by Fern from our API Definition.

import typing

from .attribute_value import AttributeValue

Attributes = typing.Dict[str, AttributeValue]
"""
A validated attribute map limited to 100 entries and 65,536 total key and
value UTF-8 bytes.

Construction and decoding reject values over these limits; an empty map
represents cleared attributes.
"""
