# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .absolute_path import AbsolutePath
from .content_ref import ContentRef
from .namespace_id import NamespaceId
from .object_transfer_access import ObjectTransferAccess
from .revision_no import RevisionNo


class BeginDownloadResponse(UniversalBaseModel):
    """
    A short-lived capability to read one file's content object, plus
    everything the reader needs to check what arrives.

    The raw object key is deliberately not here, exactly as it is not in a
    `direct_put` grant: a client learns a URL that expires, not an address it
    can revisit.

    The grant names one immutable content object, so it does not go stale
    when the path moves on. A commit that replaces the file writes a new
    object and leaves this one alone; what the capability reads is what the
    requested revision held when the grant was issued, and the reference
    says which bytes those are.
    """

    access: ObjectTransferAccess = pydantic.Field()
    """
    Short-lived read capability the client uses without learning the raw object key.
    """

    content_ref: ContentRef = pydantic.Field()
    """
    Identity, byte length, and checksum evidence for the object the
    capability reads. A reader checks the bytes it receives against
    `size_bytes` and recomputes `checksum.algorithm` over the complete
    payload.
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace that was read.
    """

    path: AbsolutePath = pydantic.Field()
    """
    Absolute path as rendered from stored display names.
    """

    revision_no: RevisionNo = pydantic.Field()
    """
    Revision the capability reads, resolved from the request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
