# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CapabilityDocument(UniversalBaseModel):
    """
    The API groups, features, and limits advertised by a deployment.
    """

    api_groups: typing.List[str] = pydantic.Field()
    """
    The advertised `group/version` API groups, each with every required operation implemented.
    """

    features: typing.Optional[typing.Dict[str, bool]] = pydantic.Field(default=None)
    """
    The named features supported by this deployment, with absent keys treated as unsupported.
    """

    limits: typing.Optional[typing.Dict[str, int]] = pydantic.Field(default=None)
    """
    Advisory numeric limits clients may use to pre-validate requests.
    """

    protocol_version: str = pydantic.Field()
    """
    The protocol generation, currently `v0`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
