# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .display_name import DisplayName
from .inode_id import InodeId


class CommitPreconditionNameAbsence(UniversalBaseModel):
    """
    Requires no visible entry with the name under the parent inode.
    """

    display_name: DisplayName = pydantic.Field()
    """
    Name to check.
    """

    parent_inode_id: InodeId = pydantic.Field()
    """
    Directory to check.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
