# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .absolute_path import AbsolutePath
from .binding_generation import BindingGeneration
from .inode_id import InodeId


class CommitAssertionBinding(UniversalBaseModel):
    """
    Requires the path to retain the binding or absence the caller read.
    """

    expected_binding_generation: typing.Optional[BindingGeneration] = pydantic.Field(default=None)
    """
    Requires an inode expectation and detects moves away and back.
    """

    expected_inode_id: typing.Optional[InodeId] = pydantic.Field(default=None)
    """
    When absent, requires the path to be unbound.
    """

    path: AbsolutePath = pydantic.Field()
    """
    Absolute path to check, including the root.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
