# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .actor_ref import ActorRef
from .change_seq import ChangeSeq
from .commit_id import CommitId
from .filesystem_change import FilesystemChange
from .namespace_id import NamespaceId


class CommitResponse(UniversalBaseModel):
    """
    The result of one commit, including its attribution and filesystem events.
    """

    commit_id: CommitId = pydantic.Field()
    """
    The idempotency key for the commit.
    """

    committed_at_ms: int = pydantic.Field()
    """
    The commit time in Unix milliseconds; `committed_seq` defines commit order.
    """

    committed_by: ActorRef = pydantic.Field()
    """
    Actor responsible for the commit, as supplied by the application.
    """

    committed_seq: ChangeSeq = pydantic.Field()
    """
    Sequence number where the commit became visible.
    """

    events: typing.Optional[typing.List[FilesystemChange]] = pydantic.Field(default=None)
    """
    The filesystem events in commit order, or `None` when replaying a commit
    without retained WAL history.
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    The optional caller annotation for the commit.
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace that changed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
