# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .inode_id import InodeId
from .revision_no import RevisionNo


class CommitPreconditionFileRevision(UniversalBaseModel):
    """
    Requires a visible inode with the content revision the caller read.
    """

    expected_revision_no: RevisionNo = pydantic.Field()
    """
    Content revision observed by the caller.
    """

    inode_id: InodeId = pydantic.Field()
    """
    Inode whose state the caller read.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
