# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CompactionStepOutcome_Fenced(UniversalBaseModel):
    """
    What the bounded compaction part of a maintenance pass did.
    """

    outcome: typing.Literal["fenced"] = "fenced"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CompactionStepOutcome_ManifestAdvanced(UniversalBaseModel):
    """
    What the bounded compaction part of a maintenance pass did.
    """

    outcome: typing.Literal["manifest_advanced"] = "manifest_advanced"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CompactionStepOutcome_MetadataCompactionRequired(UniversalBaseModel):
    """
    What the bounded compaction part of a maintenance pass did.
    """

    outcome: typing.Literal["metadata_compaction_required"] = "metadata_compaction_required"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CompactionStepOutcome_NotNeeded(UniversalBaseModel):
    """
    What the bounded compaction part of a maintenance pass did.
    """

    outcome: typing.Literal["not_needed"] = "not_needed"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CompactionStepOutcome_UnitPublished(UniversalBaseModel):
    """
    What the bounded compaction part of a maintenance pass did.
    """

    outcome: typing.Literal["unit_published"] = "unit_published"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CompactionStepOutcome = typing_extensions.Annotated[
    typing.Union[
        CompactionStepOutcome_Fenced,
        CompactionStepOutcome_ManifestAdvanced,
        CompactionStepOutcome_MetadataCompactionRequired,
        CompactionStepOutcome_NotNeeded,
        CompactionStepOutcome_UnitPublished,
    ],
    pydantic.Field(discriminator="outcome"),
]
