# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .completed_upload_part import CompletedUploadPart
from .upload_content_claim import UploadContentClaim


class CompleteUploadBody_DirectMultipart(UniversalBaseModel):
    """
    Completes an upload using the mode that started it.
    """

    mode: typing.Literal["direct_multipart"] = "direct_multipart"
    content: UploadContentClaim
    parts: typing.List[CompletedUploadPart]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CompleteUploadBody_DirectPut(UniversalBaseModel):
    """
    Completes an upload using the mode that started it.
    """

    mode: typing.Literal["direct_put"] = "direct_put"
    content: UploadContentClaim

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CompleteUploadBody_ServiceProxied(UniversalBaseModel):
    """
    Completes an upload using the mode that started it.
    """

    mode: typing.Literal["service_proxied"] = "service_proxied"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CompleteUploadBody = typing_extensions.Annotated[
    typing.Union[CompleteUploadBody_DirectMultipart, CompleteUploadBody_DirectPut, CompleteUploadBody_ServiceProxied],
    pydantic.Field(discriminator="mode"),
]
