# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DeletedObjectCounts(UniversalBaseModel):
    """
    Object counts deleted by one garbage-collection pass, grouped by family.
    """

    content_objects: int = pydantic.Field()
    """
    Content reclaimed through completed upload sessions.
    """

    manifests: int = pydantic.Field()
    """
    Unreferenced manifests deleted.
    """

    metadata_segments: int = pydantic.Field()
    """
    Unreferenced metadata segments deleted.
    """

    retired_content_objects: int = pydantic.Field()
    """
    Listed content objects deleted from a retired namespace.
    """

    upload_sessions: int = pydantic.Field()
    """
    Upload-session control objects deleted after the reap window.
    """

    wal_segments: int = pydantic.Field()
    """
    Unreferenced WAL segments deleted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
