# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .namespace_id import NamespaceId
from .snapshot_id import SnapshotId


class DeleteSnapshotResponse(UniversalBaseModel):
    """
    Identifies the snapshot record that was deleted.
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace the snapshot belonged to.
    """

    snapshot_id: SnapshotId = pydantic.Field()
    """
    Deleted snapshot record.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
