# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .error_details import ErrorDetails


class ErrorResponse(UniversalBaseModel):
    """
    HTTP error body used by LoonFS APIs.
    """

    code: str = pydantic.Field()
    """
    The stable machine-readable error code as a string.
    """

    details: typing.Optional[ErrorDetails] = pydantic.Field(default=None)
    """
    The optional machine-readable context for the error code.
    """

    feature: typing.Optional[str] = pydantic.Field(default=None)
    """
    The capability feature key for a `not_supported` error.
    """

    message: str = pydantic.Field()
    """
    Human-readable error message.
    """

    param: typing.Optional[str] = pydantic.Field(default=None)
    """
    The invalid JSON Pointer, parameter name, CLI flag, or CLI argument.
    """

    request_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The request correlation ID also sent in the `x-request-id` response header.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
