# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .absolute_path import AbsolutePath
from .change_seq import ChangeSeq
from .inode_id import InodeId


class FilesystemOperationUndelete(UniversalBaseModel):
    """
    Restore the deletion identified by `inode_id` and `deletion_seq`.
    """

    deletion_seq: ChangeSeq = pydantic.Field()
    """
    Observed deletion sequence, which prevents cancelling a newer tombstone sequence.
    """

    destination_path: typing.Optional[AbsolutePath] = pydantic.Field(default=None)
    """
    The restore destination, or `None` to use the recorded binding.
    """

    inode_id: InodeId = pydantic.Field()
    """
    Deleted inode to make reachable again.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
