# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .access_grants import AccessGrants
from .access_revision_no import AccessRevisionNo
from .inode_id import InodeId


class FilesystemOperationUpdateAccessByInode(UniversalBaseModel):
    """
    Replace the access row of a visible inode. The root inode is a valid
    target.
    """

    boundary: bool = pydantic.Field()
    """
    Whether the directory stops inheritance from its ancestors.
    """

    expected_access_revision_no: typing.Optional[AccessRevisionNo] = pydantic.Field(default=None)
    """
    The access revision that must still be current.
    """

    grants: AccessGrants = pydantic.Field()
    """
    The inode's complete direct grants after this update.
    """

    inode_id: InodeId = pydantic.Field()
    """
    Visible file or directory to update.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
