# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .binding_generation import BindingGeneration
from .destination_behavior import DestinationBehavior
from .display_name import DisplayName
from .inode_id import InodeId
from .revision_no import RevisionNo


class FilesystemOperationMoveByInode(UniversalBaseModel):
    """
    Move an inode if its current binding matches.
    """

    behavior: typing.Optional[DestinationBehavior] = pydantic.Field(default=None)
    """
    Whether an existing destination file may be replaced.
    """

    expected_binding_generation: BindingGeneration = pydantic.Field()
    """
    Binding generation required for the move.
    """

    expected_destination_inode_id: typing.Optional[InodeId] = pydantic.Field(default=None)
    """
    With `replace` behavior, the destination inode required by the request.
    """

    expected_destination_revision_no: typing.Optional[RevisionNo] = pydantic.Field(default=None)
    """
    With `replace` behavior and an inode guard, the required content revision.
    """

    inode_id: InodeId = pydantic.Field()
    """
    Inode to move.
    """

    to_display_name: DisplayName = pydantic.Field()
    """
    New name.
    """

    to_parent_inode_id: InodeId = pydantic.Field()
    """
    Destination directory.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
