# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .content_ref import ContentRef
from .inode_id import InodeId
from .revision_no import RevisionNo


class FilesystemChangeContentChanged(UniversalBaseModel):
    """
    A file received a new current revision from a put or revision restore.
    """

    content_ref: ContentRef = pydantic.Field()
    """
    Immutable content published by the revision.
    """

    inode_id: InodeId = pydantic.Field()
    """
    File inode whose history advanced.
    """

    revision_no: RevisionNo = pydantic.Field()
    """
    New monotonic position in that file's revision history.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
