# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .absolute_path import AbsolutePath
from .revision_no import RevisionNo


class FilesystemOperationRestoreRevision(UniversalBaseModel):
    """
    Restore an older revision as the current revision for a path.
    """

    path: AbsolutePath = pydantic.Field()
    """
    Absolute path that must resolve to a visible file.
    """

    source_revision_no: RevisionNo = pydantic.Field()
    """
    Existing historical revision whose content will be copied into a new current revision.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
