# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .absolute_path import AbsolutePath
from .access_grants import AccessGrants
from .access_revision_no import AccessRevisionNo
from .inode_id import InodeId


class FilesystemOperationUpdateAccess(UniversalBaseModel):
    """
    Replace the access row of the inode one path resolves to. The root
    path is a valid target.
    """

    boundary: bool = pydantic.Field()
    """
    Whether the directory stops inheritance from its ancestors.
    """

    expected_access_revision_no: typing.Optional[AccessRevisionNo] = pydantic.Field(default=None)
    """
    With an inode precondition, the access revision that must still be current.
    """

    expected_inode_id: typing.Optional[InodeId] = pydantic.Field(default=None)
    """
    The inode that the path must still resolve to before the update.
    """

    grants: AccessGrants = pydantic.Field()
    """
    The inode's complete direct grants after this update.
    """

    path: AbsolutePath = pydantic.Field()
    """
    Absolute path that must resolve to a visible file or directory.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
