# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .access_grants import AccessGrants
from .access_revision_no import AccessRevisionNo
from .inode_id import InodeId


class FilesystemChangeAccessChanged(UniversalBaseModel):
    """
    An inode's access row was replaced. `grants` is the complete
    direct grant map after the update.
    """

    access_revision_no: AccessRevisionNo = pydantic.Field()
    """
    Revision published by the update.
    """

    boundary: bool = pydantic.Field()
    """
    Whether the directory stops inheritance from its ancestors.
    """

    grants: AccessGrants = pydantic.Field()
    """
    The inode's complete direct grants after this update.
    """

    inode_id: InodeId = pydantic.Field()
    """
    Inode whose access state advanced.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
