# This file was auto-generated by Fern from our API Definition.

ManifestNo = int
"""
Monotonic manifest counter for one namespace. It can increase when metadata changes, even if no namespace commit is written.
"""
