# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .actor_id import ActorId
from .change_seq import ChangeSeq
from .manifest_no import ManifestNo
from .namespace_fork_basis import NamespaceForkBasis
from .namespace_id import NamespaceId


class NamespaceDiagnostics(UniversalBaseModel):
    """
    Namespace state and storage details used by maintenance.
    """

    created_at_ms: int = pydantic.Field()
    """
    Time the namespace was created, in Unix milliseconds.
    """

    created_by: ActorId = pydantic.Field()
    """
    Actor that created the namespace, as supplied by the application.
    """

    current_manifest_no: typing.Optional[ManifestNo] = pydantic.Field(default=None)
    """
    The namespace's current manifest number.
    """

    fork_basis: typing.Optional[NamespaceForkBasis] = pydantic.Field(default=None)
    """
    Present only for a fork: the source it was forked from.
    """

    head_seq: ChangeSeq = pydantic.Field()
    """
    Current visible namespace sequence.
    """

    live_checkpoints: int = pydantic.Field()
    """
    Number of active user checkpoints, including expired records awaiting collection.
    """

    live_snapshots: int = pydantic.Field()
    """
    Number of snapshots that had not expired when diagnostics began.
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace ID.
    """

    retention_floor_seq: ChangeSeq = pydantic.Field()
    """
    Oldest sequence still promised for incremental replay.
    """

    wal_tail_segments: int = pydantic.Field()
    """
    Number of visible WAL segments after the current manifest.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
