# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .principal_scope import PrincipalScope


class NamespaceAccessMode_Acl(UniversalBaseModel):
    """
    A namespace's access mode as reported, without its genesis grants.
    """

    kind: typing.Literal["acl"] = "acl"
    principal_scope: PrincipalScope

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NamespaceAccessMode_Unrestricted(UniversalBaseModel):
    """
    A namespace's access mode as reported, without its genesis grants.
    """

    kind: typing.Literal["unrestricted"] = "unrestricted"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


NamespaceAccessMode = typing_extensions.Annotated[
    typing.Union[NamespaceAccessMode_Acl, NamespaceAccessMode_Unrestricted], pydantic.Field(discriminator="kind")
]
