# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .principal_scope import PrincipalScope


class NamespaceAccessModeAcl(UniversalBaseModel):
    """
    Access rows govern operations in this identity domain.
    """

    principal_scope: PrincipalScope = pydantic.Field()
    """
    Identity domain the namespace's principal ids belong to.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
