# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .absolute_path import AbsolutePath
from .actor_ref import ActorRef
from .attribute_revision_no import AttributeRevisionNo
from .attributes import Attributes
from .change_seq import ChangeSeq
from .content_ref import ContentRef
from .display_name import DisplayName
from .namespace_id import NamespaceId
from .revision_no import RevisionNo


class PathEntryFile(UniversalBaseModel):
    """
    A file and its current revision summary.
    """

    content_ref: ContentRef = pydantic.Field()
    """
    Current content reference.
    """

    revision_committed_at_ms: int = pydantic.Field()
    """
    Time of the current revision, in Unix milliseconds. Revision
    sequences determine order.
    """

    revision_committed_by: ActorRef = pydantic.Field()
    """
    Actor responsible for the current revision.
    """

    revision_no: RevisionNo = pydantic.Field()
    """
    Current file revision number.
    """

    size_bytes: int = pydantic.Field()
    """
    Current file size in bytes.
    
    This remains explicit even though `content_ref` also carries the
    length because callers sort directory listings by this field.
    """

    attributes: typing.Optional[Attributes] = pydantic.Field(default=None)
    """
    The complete attribute map at `attributes_revision_no`.
    
    An inode that has never had attributes written is at revision 0 with
    an empty map.
    """

    attributes_revision_no: typing.Optional[AttributeRevisionNo] = pydantic.Field(default=None)
    """
    The attribute revision this projection represents.
    """

    attributes_updated_at_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Time of the latest attribute update, in Unix milliseconds. This is
    `None` for the initial empty state at revision 0.
    """

    attributes_updated_by: typing.Optional[ActorRef] = pydantic.Field(default=None)
    """
    Actor responsible for the latest attribute update. This is `None` for
    the initial empty state at revision 0.
    """

    binding_generation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque identifier for this entry's current parent/name binding. Absent for the namespace root.
    """

    created_at_ms: int = pydantic.Field()
    """
    Time the inode was created, in Unix milliseconds. Sequence numbers
    determine order.
    """

    created_by: ActorRef = pydantic.Field()
    """
    Actor that created this inode, as supplied by the application.
    """

    display_name: typing.Optional[DisplayName] = pydantic.Field(default=None)
    """
    Stored display name for this path component, absent for the nameless root.
    """

    head_seq: ChangeSeq = pydantic.Field()
    """
    Namespace head sequence this answer was read from.
    """

    inode_id: str = pydantic.Field()
    """
    Stable inode ID within a namespace
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace that was read.
    """

    parent_inode_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stable inode ID within a namespace
    """

    path: AbsolutePath = pydantic.Field()
    """
    Absolute path as rendered from stored display names.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
