# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ReleasedCheckpointCounts(UniversalBaseModel):
    """
    Checkpoint record counts released by one garbage-collection pass, grouped by reason.
    """

    expired: int = pydantic.Field()
    """
    User-owned records released after expiry or terminal namespace deletion.
    """

    fork: int = pydantic.Field()
    """
    Fork-owned records released because their target namespaces are gone.
    """

    snapshot: int = pydantic.Field()
    """
    Snapshot-owned records released after expiry or terminal namespace deletion.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
