# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RunMaintenanceRequestGc(UniversalBaseModel):
    """
    Runs one bounded mark-and-sweep garbage-collection pass.
    """

    cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    The opaque `next_cursor` returned by an earlier call for this namespace.
    Omitting it joins any active run; scan positions remain server-owned.
    """

    grace_window_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    The minimum object age for deletion in milliseconds, which must meet the
    server's advertised safety floor.
    """

    max_steps: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum durable GC work steps in this call; the default is 1024.
    Even a budget of one saves progress through marking and sweeping.
    This is not a limit on object-store requests or memory.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
