# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .access_revision_no import AccessRevisionNo
from .change_seq import ChangeSeq
from .commit_id import CommitId
from .deleted_checkpoints_by_owner import DeletedCheckpointsByOwner
from .deleted_object_counts import DeletedObjectCounts
from .metadata_compaction_outcome import MetadataCompactionOutcome
from .namespace_id import NamespaceId
from .reorganize_step_outcome import ReorganizeStepOutcome
from .retained_candidates import RetainedCandidates
from .wal_flush_step_outcome import WalFlushStepOutcome


class RunMaintenanceResponse_Gc(UniversalBaseModel):
    """
    The result of one maintenance job. The `kind` matches the request.
    """

    kind: typing.Literal["gc"] = "gc"
    deleted: DeletedObjectCounts
    deleted_checkpoints_by_owner: DeletedCheckpointsByOwner
    namespace_id: NamespaceId
    next_reclamation_at_ms: typing.Optional[int] = None
    reclaimable_at_ms: typing.Optional[int] = None
    retained: RetainedCandidates

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RunMaintenanceResponse_GrepGc(UniversalBaseModel):
    """
    The result of one maintenance job. The `kind` matches the request.
    """

    kind: typing.Literal["grep_gc"] = "grep_gc"
    deleted_other_objects: int
    deleted_segments: int
    namespace_id: NamespaceId
    namespace_reaped: bool
    retained_candidates: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RunMaintenanceResponse_Metadata(UniversalBaseModel):
    """
    The result of one maintenance job. The `kind` matches the request.
    """

    kind: typing.Literal["metadata"] = "metadata"
    namespace_id: NamespaceId
    reorganize: ReorganizeStepOutcome
    wal_flush: WalFlushStepOutcome

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RunMaintenanceResponse_MetadataCompaction(UniversalBaseModel):
    """
    The result of one maintenance job. The `kind` matches the request.
    """

    kind: typing.Literal["metadata_compaction"] = "metadata_compaction"
    compaction: MetadataCompactionOutcome
    namespace_id: NamespaceId

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RunMaintenanceResponse_RecoverAdministrator(UniversalBaseModel):
    """
    The result of one maintenance job. The `kind` matches the request.
    """

    kind: typing.Literal["recover_administrator"] = "recover_administrator"
    access_revision_no: AccessRevisionNo
    commit_id: CommitId
    committed_seq: ChangeSeq
    namespace_id: NamespaceId

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RunMaintenanceResponse_Retention(UniversalBaseModel):
    """
    The result of one maintenance job. The `kind` matches the request.
    """

    kind: typing.Literal["retention"] = "retention"
    namespace_id: NamespaceId
    retention_floor_seq: ChangeSeq

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


RunMaintenanceResponse = typing_extensions.Annotated[
    typing.Union[
        RunMaintenanceResponse_Gc,
        RunMaintenanceResponse_GrepGc,
        RunMaintenanceResponse_Metadata,
        RunMaintenanceResponse_MetadataCompaction,
        RunMaintenanceResponse_RecoverAdministrator,
        RunMaintenanceResponse_Retention,
    ],
    pydantic.Field(discriminator="kind"),
]
