# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deleted_object_counts import DeletedObjectCounts
from .namespace_id import NamespaceId
from .released_checkpoint_counts import ReleasedCheckpointCounts
from .retained_candidates import RetainedCandidates


class RunMaintenanceResponseGc(UniversalBaseModel):
    """
    Counts and deadlines from one collection call.
    """

    deleted: DeletedObjectCounts = pydantic.Field()
    """
    Objects the pass deleted, split by object family.
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace the pass ran against.
    """

    next_reclamation_at_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    The earliest known future reclamation time observed by this pass.
    """

    reclaim_after_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    The deleted head's irrevocable owner-prefix collection deadline.
    """

    released_checkpoints: ReleasedCheckpointCounts = pydantic.Field()
    """
    The checkpoint records released by the pass, grouped by reason.
    """

    retained: RetainedCandidates = pydantic.Field()
    """
    `retained_candidates` grouped by reason.
    """

    retained_candidates: int = pydantic.Field()
    """
    The number of candidates retained at deletion time.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
