# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .object_transfer_access import ObjectTransferAccess


class SignedUploadPart(UniversalBaseModel):
    """
    One authorized part upload.
    """

    access: ObjectTransferAccess = pydantic.Field()
    """
    Short-lived write capability for that part.
    """

    part_number: int = pydantic.Field()
    """
    Part number this capability writes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
