# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .store_probe_check_result import StoreProbeCheckResult


class StoreProbeResponse(UniversalBaseModel):
    """
    What one store contract probe observed, check by check.
    """

    checks: typing.List[StoreProbeCheckResult] = pydantic.Field()
    """
    Every check the run performed, in the order it performed them. A
    failed check lives here rather than in an error: the probe answered
    the question, and the answer is that the store is wrong.
    """

    run_id: str = pydantic.Field()
    """
    Label the server minted for this run. It scopes the objects the run
    wrote, so it identifies the run in provider logs too.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
