# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .content_ref import ContentRef
from .namespace_id import NamespaceId
from .upload_id import UploadId


class UploadContentResponse(UniversalBaseModel):
    """
    Response after uploading bytes into a session.
    """

    content_ref: ContentRef = pydantic.Field()
    """
    Digest and byte length computed from the accepted body.
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace that owns the upload session.
    """

    upload_id: UploadId = pydantic.Field()
    """
    Session into which the service staged these bytes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
