# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.change_seq import ChangeSeq
from ..types.checkpoint_id import CheckpointId
from ..types.list_changes_response import ListChangesResponse
from .raw_client import AsyncRawChangesClient, RawChangesClient


class ChangesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChangesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChangesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChangesClient
        """
        return self._raw_client

    def list(
        self,
        namespace_id: str,
        *,
        after_seq: ChangeSeq,
        limit: typing.Optional[int] = None,
        snapshot_id: typing.Optional[CheckpointId] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChangesResponse:
        """
        Returns committed changes after a sequence. A snapshot limits the feed to its captured sequence.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        after_seq : ChangeSeq
            Return committed changes after this sequence

        limit : typing.Optional[int]
            Maximum page size

        snapshot_id : typing.Optional[CheckpointId]
            End the feed at this snapshot's captured sequence

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChangesResponse
            Committed changes

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.changes.list(
            namespace_id="namespace_id",
            after_seq=1000000,
            snapshot_id="chk_00000000000000000000000000000002",
        )
        """
        _response = self._raw_client.list(
            namespace_id, after_seq=after_seq, limit=limit, snapshot_id=snapshot_id, request_options=request_options
        )
        return _response.data


class AsyncChangesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChangesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChangesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChangesClient
        """
        return self._raw_client

    async def list(
        self,
        namespace_id: str,
        *,
        after_seq: ChangeSeq,
        limit: typing.Optional[int] = None,
        snapshot_id: typing.Optional[CheckpointId] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChangesResponse:
        """
        Returns committed changes after a sequence. A snapshot limits the feed to its captured sequence.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        after_seq : ChangeSeq
            Return committed changes after this sequence

        limit : typing.Optional[int]
            Maximum page size

        snapshot_id : typing.Optional[CheckpointId]
            End the feed at this snapshot's captured sequence

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChangesResponse
            Committed changes

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.changes.list(
                namespace_id="namespace_id",
                after_seq=1000000,
                snapshot_id="chk_00000000000000000000000000000002",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            namespace_id, after_seq=after_seq, limit=limit, snapshot_id=snapshot_id, request_options=request_options
        )
        return _response.data
