# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.list_snapshots_response import ListSnapshotsResponse
from ..types.release_snapshot_response import ReleaseSnapshotResponse
from ..types.snapshot import Snapshot
from .raw_client import AsyncRawSnapshotsClient, RawSnapshotsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SnapshotsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSnapshotsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSnapshotsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSnapshotsClient
        """
        return self._raw_client

    def list(
        self,
        namespace_id: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSnapshotsResponse:
        """
        Lists live snapshots in snapshot-id order. Released and expired snapshots are omitted.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        limit : typing.Optional[int]
            Maximum page size

        cursor : typing.Optional[str]
            Opaque snapshot-list page cursor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSnapshotsResponse
            Live snapshots

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.snapshots.list(
            namespace_id="namespace_id",
        )
        """
        _response = self._raw_client.list(namespace_id, limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    def create(
        self, namespace_id: str, *, name: str, ttl_ms: int, request_options: typing.Optional[RequestOptions] = None
    ) -> Snapshot:
        """
        Creates a snapshot of the current namespace state. Every call creates a new snapshot.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        name : str
            A label that does not need to be unique.

        ttl_ms : int
            Snapshot lifetime from the current server time, in milliseconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Snapshot
            Snapshot created

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.snapshots.create(
            namespace_id="namespace_id",
            name="name",
            ttl_ms=1000000,
        )
        """
        _response = self._raw_client.create(namespace_id, name=name, ttl_ms=ttl_ms, request_options=request_options)
        return _response.data

    def extend(
        self,
        namespace_id: str,
        snapshot_id: str,
        *,
        ttl_ms: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Snapshot:
        """
        Extends a live snapshot without passing its lifetime limit. Repeating the request has the same result.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        snapshot_id : str
            Snapshot id

        ttl_ms : int
            Requested lifetime from the server's current time, in milliseconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Snapshot
            Snapshot extended

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.snapshots.extend(
            namespace_id="namespace_id",
            snapshot_id="snapshot_id",
            ttl_ms=1000000,
        )
        """
        _response = self._raw_client.extend(namespace_id, snapshot_id, ttl_ms=ttl_ms, request_options=request_options)
        return _response.data

    def release(
        self, namespace_id: str, snapshot_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ReleaseSnapshotResponse:
        """
        Releases a snapshot by id. Repeated releases succeed.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        snapshot_id : str
            Snapshot id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReleaseSnapshotResponse
            Snapshot release accepted

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.snapshots.release(
            namespace_id="namespace_id",
            snapshot_id="snapshot_id",
        )
        """
        _response = self._raw_client.release(namespace_id, snapshot_id, request_options=request_options)
        return _response.data


class AsyncSnapshotsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSnapshotsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSnapshotsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSnapshotsClient
        """
        return self._raw_client

    async def list(
        self,
        namespace_id: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSnapshotsResponse:
        """
        Lists live snapshots in snapshot-id order. Released and expired snapshots are omitted.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        limit : typing.Optional[int]
            Maximum page size

        cursor : typing.Optional[str]
            Opaque snapshot-list page cursor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSnapshotsResponse
            Live snapshots

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.snapshots.list(
                namespace_id="namespace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            namespace_id, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def create(
        self, namespace_id: str, *, name: str, ttl_ms: int, request_options: typing.Optional[RequestOptions] = None
    ) -> Snapshot:
        """
        Creates a snapshot of the current namespace state. Every call creates a new snapshot.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        name : str
            A label that does not need to be unique.

        ttl_ms : int
            Snapshot lifetime from the current server time, in milliseconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Snapshot
            Snapshot created

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.snapshots.create(
                namespace_id="namespace_id",
                name="name",
                ttl_ms=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            namespace_id, name=name, ttl_ms=ttl_ms, request_options=request_options
        )
        return _response.data

    async def extend(
        self,
        namespace_id: str,
        snapshot_id: str,
        *,
        ttl_ms: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Snapshot:
        """
        Extends a live snapshot without passing its lifetime limit. Repeating the request has the same result.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        snapshot_id : str
            Snapshot id

        ttl_ms : int
            Requested lifetime from the server's current time, in milliseconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Snapshot
            Snapshot extended

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.snapshots.extend(
                namespace_id="namespace_id",
                snapshot_id="snapshot_id",
                ttl_ms=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.extend(
            namespace_id, snapshot_id, ttl_ms=ttl_ms, request_options=request_options
        )
        return _response.data

    async def release(
        self, namespace_id: str, snapshot_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ReleaseSnapshotResponse:
        """
        Releases a snapshot by id. Repeated releases succeed.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        snapshot_id : str
            Snapshot id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReleaseSnapshotResponse
            Snapshot release accepted

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.snapshots.release(
                namespace_id="namespace_id",
                snapshot_id="snapshot_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.release(namespace_id, snapshot_id, request_options=request_options)
        return _response.data
