# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.checkpoint import Checkpoint
from ...types.list_checkpoints_response import ListCheckpointsResponse
from ...types.release_checkpoint_response import ReleaseCheckpointResponse
from .raw_client import AsyncRawCheckpointsClient, RawCheckpointsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CheckpointsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCheckpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCheckpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCheckpointsClient
        """
        return self._raw_client

    def list(
        self,
        namespace_id: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCheckpointsResponse:
        """
        Lists one page of active checkpoints in checkpoint-id order. Expired checkpoints remain visible until collection releases them. Released checkpoints are omitted. The cursor resumes a live listing and does not create a snapshot.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        limit : typing.Optional[int]
            Maximum page size

        cursor : typing.Optional[str]
            Opaque checkpoint-list page cursor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCheckpointsResponse
            Active checkpoint objects

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.admin.checkpoints.list(
            namespace_id="namespace_id",
        )
        """
        _response = self._raw_client.list(namespace_id, limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    def create(
        self,
        namespace_id: str,
        *,
        name: str,
        ttl_ms: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Checkpoint:
        """
        Creates a named, user-owned checkpoint record pinning the current namespace view. Every call mints a new record under a new id; the name is a label, not a key. The record is a garbage-collection root until it is released, so routine maintenance should flush the WAL instead. This is a maintenance/admin operation, not a file mutation.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        name : str
            Label recorded on the checkpoint record. A label, not a key: several
            records may carry the same name over different bases.

        ttl_ms : typing.Optional[int]
            Optional lifetime; the server computes the record's expiry from its
            own clock. Absent means the pin holds until explicitly released.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Checkpoint
            The created checkpoint

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.admin.checkpoints.create(
            namespace_id="namespace_id",
            name="name",
        )
        """
        _response = self._raw_client.create(namespace_id, name=name, ttl_ms=ttl_ms, request_options=request_options)
        return _response.data

    def release(
        self, namespace_id: str, checkpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ReleaseCheckpointResponse:
        """
        Releases a user-owned checkpoint pin by id. Idempotent: releasing an already-released or reaped record succeeds. The record is reaped by a later garbage-collection pass; its pinned data becomes collectable only on the pass after that.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        checkpoint_id : str
            Checkpoint id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReleaseCheckpointResponse
            Checkpoint release accepted (including an already released or reaped checkpoint)

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.admin.checkpoints.release(
            namespace_id="namespace_id",
            checkpoint_id="checkpoint_id",
        )
        """
        _response = self._raw_client.release(namespace_id, checkpoint_id, request_options=request_options)
        return _response.data


class AsyncCheckpointsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCheckpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCheckpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCheckpointsClient
        """
        return self._raw_client

    async def list(
        self,
        namespace_id: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCheckpointsResponse:
        """
        Lists one page of active checkpoints in checkpoint-id order. Expired checkpoints remain visible until collection releases them. Released checkpoints are omitted. The cursor resumes a live listing and does not create a snapshot.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        limit : typing.Optional[int]
            Maximum page size

        cursor : typing.Optional[str]
            Opaque checkpoint-list page cursor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCheckpointsResponse
            Active checkpoint objects

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.admin.checkpoints.list(
                namespace_id="namespace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            namespace_id, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        namespace_id: str,
        *,
        name: str,
        ttl_ms: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Checkpoint:
        """
        Creates a named, user-owned checkpoint record pinning the current namespace view. Every call mints a new record under a new id; the name is a label, not a key. The record is a garbage-collection root until it is released, so routine maintenance should flush the WAL instead. This is a maintenance/admin operation, not a file mutation.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        name : str
            Label recorded on the checkpoint record. A label, not a key: several
            records may carry the same name over different bases.

        ttl_ms : typing.Optional[int]
            Optional lifetime; the server computes the record's expiry from its
            own clock. Absent means the pin holds until explicitly released.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Checkpoint
            The created checkpoint

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.admin.checkpoints.create(
                namespace_id="namespace_id",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            namespace_id, name=name, ttl_ms=ttl_ms, request_options=request_options
        )
        return _response.data

    async def release(
        self, namespace_id: str, checkpoint_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ReleaseCheckpointResponse:
        """
        Releases a user-owned checkpoint pin by id. Idempotent: releasing an already-released or reaped record succeeds. The record is reaped by a later garbage-collection pass; its pinned data becomes collectable only on the pass after that.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        checkpoint_id : str
            Checkpoint id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReleaseCheckpointResponse
            Checkpoint release accepted (including an already released or reaped checkpoint)

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.admin.checkpoints.release(
                namespace_id="namespace_id",
                checkpoint_id="checkpoint_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.release(namespace_id, checkpoint_id, request_options=request_options)
        return _response.data
