# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .actor_id import ActorId
from .actor_kind import ActorKind


class ActorRef(UniversalBaseModel):
    """
    Identifies the user, service, or system responsible for a commit.

    LoonFS stores this value as provided. It does not authenticate the actor or
    look up profile information.
    """

    id: ActorId = pydantic.Field()
    """
    A stable identifier supplied by the application.
    """

    kind: ActorKind = pydantic.Field()
    """
    The type of actor.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
