# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .actor_ref import ActorRef
from .content_ref import ContentRef
from .revision_no import RevisionNo


class AuthoritativePathEntryFile(UniversalBaseModel):
    """
    A file and its current revision summary.
    """

    content_ref: ContentRef = pydantic.Field()
    """
    Current content reference.
    """

    revision_committed_at_ms: int = pydantic.Field()
    """
    Time of the current revision, in Unix milliseconds. Revision
    sequences determine order.
    """

    revision_committed_by: ActorRef = pydantic.Field()
    """
    Actor responsible for the current revision.
    """

    revision_no: RevisionNo = pydantic.Field()
    """
    Current file revision number.
    """

    size_bytes: int = pydantic.Field()
    """
    Current file size in bytes.
    
    This remains explicit even though `content_ref` also carries the
    length because callers sort directory listings by this field.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
