# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .direct_multipart_upload_options import DirectMultipartUploadOptions


class BeginUploadDirectMultipart(UniversalBaseModel):
    """
    Write the object in parts through presigned part uploads.
    """

    multipart: typing.Optional[DirectMultipartUploadOptions] = pydantic.Field(default=None)
    """
    Part size options. The server uses its default when omitted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
