# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .direct_multipart_upload import DirectMultipartUpload
from .namespace_id import NamespaceId
from .upload_id import UploadId


class BeginUploadResponseDirectMultipart(UniversalBaseModel):
    """
    Presigned part uploads assemble the object.
    """

    direct_multipart: DirectMultipartUpload = pydantic.Field()
    """
    The geometry the client cuts its payload to.
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace authorized to consume the eventual staged content.
    """

    upload_id: UploadId = pydantic.Field()
    """
    Durable session identity used by subsequent part-signing and
    completion calls.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
