# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CapabilityDocument(UniversalBaseModel):
    """
    A deployment's self-description (API spec, "Capability discovery").

    A remote client fetches this from `GET /v0/capabilities` and caches it; an
    embedded engine exposes the same document as a constant. SDK gating logic
    is therefore identical for both backends: check [`supports`] or
    [`has_profile`], and treat a `not_supported` error as authoritative when
    the two disagree.

    [`supports`]: CapabilityDocument::supports
    [`has_profile`]: CapabilityDocument::has_profile
    """

    features: typing.Optional[typing.Dict[str, bool]] = pydantic.Field(default=None)
    """
    Named features and whether this deployment supports them. An absent
    key means unsupported.
    """

    limits: typing.Optional[typing.Dict[str, int]] = pydantic.Field(default=None)
    """
    Advisory numeric limits clients may use to pre-validate requests.
    """

    profiles: typing.List[str] = pydantic.Field()
    """
    Advertised profiles, each `plane/version`. All-or-nothing: every
    required op of an advertised profile is implemented.
    """

    protocol_version: str = pydantic.Field()
    """
    The protocol generation, currently `v0`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
