# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .change_seq import ChangeSeq
from .checkpoint_id import CheckpointId
from .checkpoint_owner_summary import CheckpointOwnerSummary
from .manifest_id import ManifestId


class Checkpoint(UniversalBaseModel):
    """
    One checkpoint resource, reported from what its durable record carries.
    """

    checkpoint_id: CheckpointId = pydantic.Field()
    """
    Durable checkpoint id used to address the checkpoint for release.
    """

    checkpoint_seq: ChangeSeq = pydantic.Field()
    """
    Sequence covered by the checkpoint's pinned basis.
    """

    created_at_ms: int = pydantic.Field()
    """
    Time the checkpoint record was created, in Unix milliseconds.
    """

    expires_at_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    When garbage collection may release the record without being asked,
    in Unix milliseconds. Absent means the pin holds until it is
    released. An instant already in the past is a record whose expiry
    has passed and which no collection pass has reached yet: it is still
    a root, so it is still listed.
    """

    manifest_id: ManifestId = pydantic.Field()
    """
    Manifest pinned by the checkpoint.
    """

    owner: CheckpointOwnerSummary = pydantic.Field()
    """
    Who owns the checkpoint, including the label carried by a user pin.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
