# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CheckpointOwnerUser(UniversalBaseModel):
    """
    An operator-created pin, released by id or by its own expiry.
    """

    name: str = pydantic.Field()
    """
    The label the creator recorded. Not a key: several records may
    carry one label over different bases.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
