# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CheckpointOwnerSnapshot(UniversalBaseModel):
    """
    An application-created read view.
    """

    expires_at_ms: int = pydantic.Field()
    """
    When the snapshot lease expires, in Unix milliseconds.
    """

    name: str = pydantic.Field()
    """
    A label that does not need to be unique.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
