# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .namespace_id import NamespaceId


class CheckpointOwnerSummary_User(UniversalBaseModel):
    """
    Who a checkpoint record answers to, as the record durably records it.

    The two owners have different releases, so a listing that names the
    owner also says which records the release endpoint will act on: a user
    pin is released by id, and a fork lease is released by deleting the
    target namespace it protects.
    """

    kind: typing.Literal["user"] = "user"
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CheckpointOwnerSummary_Fork(UniversalBaseModel):
    """
    Who a checkpoint record answers to, as the record durably records it.

    The two owners have different releases, so a listing that names the
    owner also says which records the release endpoint will act on: a user
    pin is released by id, and a fork lease is released by deleting the
    target namespace it protects.
    """

    kind: typing.Literal["fork"] = "fork"
    target_namespace_id: NamespaceId

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CheckpointOwnerSummary = typing_extensions.Annotated[
    typing.Union[CheckpointOwnerSummary_User, CheckpointOwnerSummary_Fork], pydantic.Field(discriminator="kind")
]
