# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .namespace_id import NamespaceId


class CheckpointOwnerSummary_User(UniversalBaseModel):
    """
    The owner of a checkpoint record.
    """

    kind: typing.Literal["user"] = "user"
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CheckpointOwnerSummary_Fork(UniversalBaseModel):
    """
    The owner of a checkpoint record.
    """

    kind: typing.Literal["fork"] = "fork"
    target_namespace_id: NamespaceId

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CheckpointOwnerSummary_Snapshot(UniversalBaseModel):
    """
    The owner of a checkpoint record.
    """

    kind: typing.Literal["snapshot"] = "snapshot"
    expires_at_ms: int
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CheckpointOwnerSummary = typing_extensions.Annotated[
    typing.Union[CheckpointOwnerSummary_User, CheckpointOwnerSummary_Fork, CheckpointOwnerSummary_Snapshot],
    pydantic.Field(discriminator="kind"),
]
