# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checksum import Checksum


class CompletedUploadPart(UniversalBaseModel):
    """
    One uploaded part, as the client observed the provider accept it.

    The server keeps no durable record of any part. Part bookkeeping is the
    client's, exactly as it is in the provider's own multipart API, and this
    is where the client hands it back.
    """

    checksum: Checksum = pydantic.Field()
    """
    Checksum the part was signed and accepted with.
    """

    etag: str = pydantic.Field()
    """
    Entity tag the provider returned for the accepted part.
    """

    part_number: int = pydantic.Field()
    """
    One-based part number.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
