# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checksum import Checksum
from .content_id import ContentId


class ContentRef(UniversalBaseModel):
    """
    Pointer to one immutable content object.

    `content_id` is identity — *which* object — and the checksum is
    evidence about its bytes. Separating the two is what lets the final
    object key exist before the first byte is read.

    A `ContentRef` is safe to publish only after the referenced bytes are
    durable in the namespace's content store.
    """

    checksum: Checksum = pydantic.Field()
    """
    Mandatory checksum over the complete object.
    """

    content_id: ContentId = pydantic.Field()
    """
    Immutable identity of the referenced object.
    """

    kind: str = pydantic.Field()
    """
    Content strategy used by the referenced object.
    """

    size_bytes: int = pydantic.Field()
    """
    Complete byte length of the referenced content.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
