# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .checkpoint import Checkpoint
from .namespace_id import NamespaceId


class CreateCheckpointResponse(Checkpoint):
    """
    Result of creating a checkpoint.
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace that was checkpointed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
