# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checksum_algorithm import ChecksumAlgorithm


class DirectMultipartUpload(UniversalBaseModel):
    """
    Settings returned for a direct multipart upload.
    """

    checksum_algorithm: ChecksumAlgorithm = pydantic.Field()
    """
    Checksum algorithm for every part and for the complete payload.
    """

    part_size_bytes: int = pydantic.Field()
    """
    Byte length of every part except the last. At most 10,000 parts may
    be uploaded, so this bounds the object at `part_size_bytes × 10_000`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
