# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .actor_ref import ActorRef
from .change_seq import ChangeSeq
from .commit_id import CommitId
from .content_ref import ContentRef
from .revision_no import RevisionNo


class FileRevision(UniversalBaseModel):
    """
    One immutable file revision.
    """

    commit_id: CommitId = pydantic.Field()
    """
    Commit ID for this revision.
    """

    committed_at_ms: int = pydantic.Field()
    """
    Wall-clock stamp of the commit that created this revision, in Unix
    milliseconds. Observational: `committed_seq` is the order.
    """

    committed_by: ActorRef = pydantic.Field()
    """
    Actor responsible for this revision, as supplied by the application.
    """

    committed_seq: ChangeSeq = pydantic.Field()
    """
    Namespace sequence that created this revision.
    """

    content_ref: ContentRef = pydantic.Field()
    """
    Content stored for this revision.
    """

    inode_id: str = pydantic.Field()
    """
    Stable inode ID within a namespace
    """

    revision_no: RevisionNo = pydantic.Field()
    """
    Revision number within the file inode.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
