# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deleted_direntry import DeletedDirentry


class FilesystemChangeDeleted(UniversalBaseModel):
    """
    A file or directory subtree was deleted. Use the enclosing change's
    `committed_seq` as `deletion_seq` when restoring it.
    """

    deleted_direntry: typing.Optional[DeletedDirentry] = pydantic.Field(default=None)
    """
    Directory binding removed by the deletion, when the delete
    recorded one.
    """

    inode_id: str = pydantic.Field()
    """
    Stable inode ID within a namespace
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
