# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .delete_directory_behavior import DeleteDirectoryBehavior


class FilesystemOperationDeleteByInode(UniversalBaseModel):
    """
    Delete an inode if its current binding matches.
    """

    behavior: typing.Optional[DeleteDirectoryBehavior] = pydantic.Field(default=None)
    """
    Whether a non-empty directory may be tombstoned recursively.
    """

    expected_binding_generation: str = pydantic.Field()
    """
    Binding generation required for the delete.
    """

    inode_id: str = pydantic.Field()
    """
    Stable inode ID within a namespace
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
