# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .absolute_path import AbsolutePath
from .delete_directory_behavior import DeleteDirectoryBehavior


class FsOpDeletePath(UniversalBaseModel):
    """
    Delete one path.
    """

    behavior: typing.Optional[DeleteDirectoryBehavior] = pydantic.Field(default=None)
    """
    Whether a non-empty directory may be tombstoned recursively.
    """

    expected_inode_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stable inode ID within a namespace
    """

    path: AbsolutePath = pydantic.Field()
    """
    Absolute path that must resolve to a visible inode.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
