# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .absolute_path import AbsolutePath
from .attribute_key import AttributeKey
from .attribute_revision_no import AttributeRevisionNo
from .attribute_value import AttributeValue


class FsOpUpdateAttributes(UniversalBaseModel):
    """
    Write and remove attributes on the inode one path resolves to.
    """

    expected_attributes_revision_no: typing.Optional[AttributeRevisionNo] = pydantic.Field(default=None)
    """
    When set, the update applies only while the inode's attribute
    revision is still this one. Absent means the update is applied
    over whatever revision is current; either way the write carries
    its own revision guard, so a concurrent update never merges
    silently.
    """

    expected_inode_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stable inode ID within a namespace
    """

    path: AbsolutePath = pydantic.Field()
    """
    Absolute path that must resolve to a visible file or directory.
    """

    remove: typing.Optional[typing.List[AttributeKey]] = pydantic.Field(default=None)
    """
    Attribute keys to remove.
    
    A list preserves duplicate entries so validation can report them instead
    of silently deduplicating the request.
    """

    set_: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, AttributeValue]],
        FieldMetadata(alias="set"),
        pydantic.Field(
            alias="set",
            description="Attributes to write. Each key replaces whatever the inode\ncurrently holds under it; keys the inode holds and this map does\nnot name are left alone.",
        ),
    ] = None
    """
    Attributes to write. Each key replaces whatever the inode
    currently holds under it; keys the inode holds and this map does
    not name are left alone.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
