# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .absolute_path import AbsolutePath
from .content_ref import ContentRef
from .destination_behavior import DestinationBehavior
from .revision_no import RevisionNo


class FsOpPutFile(UniversalBaseModel):
    """
    Create or replace one file with an already-durable content ref.
    """

    behavior: typing.Optional[DestinationBehavior] = pydantic.Field(default=None)
    """
    Whether an existing file may receive a new revision instead of causing a conflict.
    """

    content_ref: ContentRef = pydantic.Field()
    """
    Immutable bytes that must be covered by a valid preparation proof.
    """

    expected_revision_no: typing.Optional[RevisionNo] = pydantic.Field(default=None)
    """
    When set (with `replace` behavior), the put applies only while
    the file's current revision is still this one; a raced write
    fails the request instead of silently stacking on it, and a
    missing file answers `path_not_found`.
    """

    path: AbsolutePath = pydantic.Field()
    """
    Absolute destination path; missing ancestors are created automatically.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
