# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .absolute_path import AbsolutePath
from .revision_no import RevisionNo


class GrepMatch(UniversalBaseModel):
    """
    One line-oriented match.
    """

    byte_offset: int = pydantic.Field()
    """
    Byte offset of the match within the file.
    """

    inode_id: str = pydantic.Field()
    """
    Stable inode ID within a namespace
    """

    line: str = pydantic.Field()
    """
    The matching line, truncated to the server's line cap.
    """

    line_number: int = pydantic.Field()
    """
    One-based line number of the match.
    """

    line_truncated: bool = pydantic.Field()
    """
    True when `line` was truncated.
    """

    path: AbsolutePath = pydantic.Field()
    """
    The file's absolute path, derived at the snapshot.
    """

    revision_no: RevisionNo = pydantic.Field()
    """
    The matched revision (the newest visible one at the snapshot).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
