# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .advance_retention_response import AdvanceRetentionResponse
from .gc_response import GcResponse
from .metadata_maintenance_response import MetadataMaintenanceResponse
from .namespace_diagnostics import NamespaceDiagnostics
from .namespace_id import NamespaceId


class MaintenanceStepResponse(UniversalBaseModel):
    """
    Result of one explicit maintenance step.

    One report per action the request selected, and none for an action it
    did not: an absent field means "not selected", never "ran and found
    nothing to do". The latter is what the outcomes inside a report say.
    """

    gc: typing.Optional[GcResponse] = pydantic.Field(default=None)
    """
    What the collection pass reclaimed.
    """

    metadata: typing.Optional[MetadataMaintenanceResponse] = pydantic.Field(default=None)
    """
    What the metadata-upkeep action did.
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace the step ran against.
    """

    retention: typing.Optional[AdvanceRetentionResponse] = pydantic.Field(default=None)
    """
    Where the retention floor ended up.
    """

    status_before: NamespaceDiagnostics = pydantic.Field()
    """
    Namespace diagnostics observed before the step acted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
