# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .change_seq import ChangeSeq
from .manifest_id import ManifestId
from .namespace_id import NamespaceId


class NamespaceDiagnostics(UniversalBaseModel):
    """
    Namespace state and storage details used by maintenance.
    """

    current_manifest_id: typing.Optional[ManifestId] = pydantic.Field(default=None)
    """
    Current manifest pointer recorded by the head.
    """

    head_seq: ChangeSeq = pydantic.Field()
    """
    Current visible namespace sequence.
    """

    namespace_id: NamespaceId = pydantic.Field()
    """
    Namespace ID.
    """

    retention_floor_seq: ChangeSeq = pydantic.Field()
    """
    Oldest sequence still promised for incremental replay.
    """

    wal_tail_segments: int = pydantic.Field()
    """
    Number of visible WAL segments after the current manifest.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
