# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .absolute_path import AbsolutePath
from .actor_ref import ActorRef
from .attribute_revision_no import AttributeRevisionNo
from .attributes import Attributes
from .change_seq import ChangeSeq
from .content_ref import ContentRef
from .display_name import DisplayName
from .namespace_id import NamespaceId
from .revision_no import RevisionNo


class PathEntry_Dir(UniversalBaseModel):
    """
    Metadata for one path returned by stat and directory-listing operations.

    File entries include the current revision and content details. Directory
    entries do not. Attribute fields are included only when requested and are
    serialized at the top level of the entry. Callers can pass
    `attributes_revision_no` as `expected_attributes_revision_no` when updating
    attributes.
    """

    inode_kind: typing.Literal["dir"] = "dir"
    attributes: typing.Optional[Attributes] = None
    attributes_revision_no: typing.Optional[AttributeRevisionNo] = None
    attributes_updated_at_ms: typing.Optional[int] = None
    attributes_updated_by: typing.Optional[ActorRef] = None
    binding_generation: typing.Optional[str] = None
    created_at_ms: int
    created_by: ActorRef
    display_name: typing.Optional[DisplayName] = None
    head_seq: ChangeSeq
    inode_id: str
    namespace_id: NamespaceId
    parent_inode_id: typing.Optional[str] = None
    path: AbsolutePath

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PathEntry_File(UniversalBaseModel):
    """
    Metadata for one path returned by stat and directory-listing operations.

    File entries include the current revision and content details. Directory
    entries do not. Attribute fields are included only when requested and are
    serialized at the top level of the entry. Callers can pass
    `attributes_revision_no` as `expected_attributes_revision_no` when updating
    attributes.
    """

    inode_kind: typing.Literal["file"] = "file"
    content_ref: ContentRef
    revision_committed_at_ms: int
    revision_committed_by: ActorRef
    revision_no: RevisionNo
    size_bytes: int
    attributes: typing.Optional[Attributes] = None
    attributes_revision_no: typing.Optional[AttributeRevisionNo] = None
    attributes_updated_at_ms: typing.Optional[int] = None
    attributes_updated_by: typing.Optional[ActorRef] = None
    binding_generation: typing.Optional[str] = None
    created_at_ms: int
    created_by: ActorRef
    display_name: typing.Optional[DisplayName] = None
    head_seq: ChangeSeq
    inode_id: str
    namespace_id: NamespaceId
    parent_inode_id: typing.Optional[str] = None
    path: AbsolutePath

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


PathEntry = typing_extensions.Annotated[
    typing.Union[PathEntry_Dir, PathEntry_File], pydantic.Field(discriminator="inode_kind")
]
