# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ReleasedCheckpointCounts(UniversalBaseModel):
    """
    Checkpoint records released by one GC pass, grouped by reason.

    Releasing a record stops it from pinning data. A later pass may delete the
    record after its grace window and count that under
    [`DeletedObjectCounts::checkpoint_records`].
    """

    expired: int = pydantic.Field()
    """
    User-owned records released because their expiry passed, or because
    they sit on a terminally deleted namespace.
    """

    fork: int = pydantic.Field()
    """
    Fork-owned records released because their target namespace is
    provably gone.
    """

    missing_basis: int = pydantic.Field()
    """
    Active records released because their basis manifest is verifiably
    gone.
    """

    snapshot: int = pydantic.Field()
    """
    Snapshot-owned records released because their expiry passed, or
    because they sit on a terminally deleted namespace.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
