# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UploadSessionStatusOpen(UniversalBaseModel):
    """
    Accepting content until its lease passes.
    """

    expires_at_ms: int = pydantic.Field()
    """
    Unix-millisecond instant after which the session is abandoned and
    may be aborted by server-side cleanup.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
