# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .change_seq import ChangeSeq
from .manifest_no import ManifestNo


class WalFlushStepOutcomeAlreadyPublished(UniversalBaseModel):
    """
    The step did not update the root because it already referenced a
    different manifest.
    """

    attempted_seq: ChangeSeq = pydantic.Field()
    """
    Sequence this step attempted to flush through.
    """

    current_manifest_no: ManifestNo = pydantic.Field()
    """
    Manifest the root currently references.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
