# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.change_seq import ChangeSeq
from ..types.delete_namespace_response import DeleteNamespaceResponse
from ..types.namespace import Namespace
from ..types.namespace_access import NamespaceAccess
from ..types.namespace_id import NamespaceId
from ..types.pin_id import PinId
from .raw_client import AsyncRawNamespacesClient, RawNamespacesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class NamespacesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawNamespacesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawNamespacesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawNamespacesClient
        """
        return self._raw_client

    def create(
        self,
        *,
        namespace_id: NamespaceId,
        access: typing.Optional[NamespaceAccess] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Namespace:
        """
        Creates a new empty namespace.

        Parameters
        ----------
        namespace_id : NamespaceId
            Durable namespace id to create.

        access : typing.Optional[NamespaceAccess]
            The access mode, fixed for the namespace's life. Defaults to
            unrestricted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Namespace
            Namespace created

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            actor_id="YOUR_ACTOR_ID",
            subject_id="YOUR_SUBJECT_ID",
            principal_scope="YOUR_PRINCIPAL_SCOPE",
            principals="YOUR_PRINCIPALS",
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.namespaces.create(
            namespace_id="demo",
        )
        """
        _response = self._raw_client.create(namespace_id=namespace_id, access=access, request_options=request_options)
        return _response.data

    def retrieve(self, namespace_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Namespace:
        """
        Returns the current head and retention state for a namespace.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Namespace
            Namespace

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            actor_id="YOUR_ACTOR_ID",
            subject_id="YOUR_SUBJECT_ID",
            principal_scope="YOUR_PRINCIPAL_SCOPE",
            principals="YOUR_PRINCIPALS",
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.namespaces.retrieve(
            namespace_id="namespace_id",
        )
        """
        _response = self._raw_client.retrieve(namespace_id, request_options=request_options)
        return _response.data

    def delete(
        self,
        namespace_id: str,
        *,
        expected_head_seq: typing.Optional[ChangeSeq] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteNamespaceResponse:
        """
        Marks a namespace as deleted. The id can never be created or forked into again.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        expected_head_seq : typing.Optional[ChangeSeq]
            Delete only if the namespace head is still at this sequence

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteNamespaceResponse
            Namespace deleted

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            actor_id="YOUR_ACTOR_ID",
            subject_id="YOUR_SUBJECT_ID",
            principal_scope="YOUR_PRINCIPAL_SCOPE",
            principals="YOUR_PRINCIPALS",
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.namespaces.delete(
            namespace_id="namespace_id",
        )
        """
        _response = self._raw_client.delete(
            namespace_id, expected_head_seq=expected_head_seq, request_options=request_options
        )
        return _response.data

    def fork(
        self,
        namespace_id: str,
        *,
        new_namespace_id: NamespaceId,
        snapshot_id: typing.Optional[PinId] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Namespace:
        """
        Creates a new namespace from the source current head or a live snapshot.

        Parameters
        ----------
        namespace_id : str
            Source namespace id

        new_namespace_id : NamespaceId
            Durable namespace id for the fork target.

        snapshot_id : typing.Optional[PinId]
            Fork from this live snapshot instead of the current head.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Namespace
            Namespace forked

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            actor_id="YOUR_ACTOR_ID",
            subject_id="YOUR_SUBJECT_ID",
            principal_scope="YOUR_PRINCIPAL_SCOPE",
            principals="YOUR_PRINCIPALS",
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.namespaces.fork(
            namespace_id="namespace_id",
            new_namespace_id="demo",
        )
        """
        _response = self._raw_client.fork(
            namespace_id, new_namespace_id=new_namespace_id, snapshot_id=snapshot_id, request_options=request_options
        )
        return _response.data


class AsyncNamespacesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawNamespacesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawNamespacesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawNamespacesClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        namespace_id: NamespaceId,
        access: typing.Optional[NamespaceAccess] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Namespace:
        """
        Creates a new empty namespace.

        Parameters
        ----------
        namespace_id : NamespaceId
            Durable namespace id to create.

        access : typing.Optional[NamespaceAccess]
            The access mode, fixed for the namespace's life. Defaults to
            unrestricted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Namespace
            Namespace created

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            actor_id="YOUR_ACTOR_ID",
            subject_id="YOUR_SUBJECT_ID",
            principal_scope="YOUR_PRINCIPAL_SCOPE",
            principals="YOUR_PRINCIPALS",
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.namespaces.create(
                namespace_id="demo",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            namespace_id=namespace_id, access=access, request_options=request_options
        )
        return _response.data

    async def retrieve(
        self, namespace_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Namespace:
        """
        Returns the current head and retention state for a namespace.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Namespace
            Namespace

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            actor_id="YOUR_ACTOR_ID",
            subject_id="YOUR_SUBJECT_ID",
            principal_scope="YOUR_PRINCIPAL_SCOPE",
            principals="YOUR_PRINCIPALS",
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.namespaces.retrieve(
                namespace_id="namespace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(namespace_id, request_options=request_options)
        return _response.data

    async def delete(
        self,
        namespace_id: str,
        *,
        expected_head_seq: typing.Optional[ChangeSeq] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteNamespaceResponse:
        """
        Marks a namespace as deleted. The id can never be created or forked into again.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        expected_head_seq : typing.Optional[ChangeSeq]
            Delete only if the namespace head is still at this sequence

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteNamespaceResponse
            Namespace deleted

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            actor_id="YOUR_ACTOR_ID",
            subject_id="YOUR_SUBJECT_ID",
            principal_scope="YOUR_PRINCIPAL_SCOPE",
            principals="YOUR_PRINCIPALS",
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.namespaces.delete(
                namespace_id="namespace_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            namespace_id, expected_head_seq=expected_head_seq, request_options=request_options
        )
        return _response.data

    async def fork(
        self,
        namespace_id: str,
        *,
        new_namespace_id: NamespaceId,
        snapshot_id: typing.Optional[PinId] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Namespace:
        """
        Creates a new namespace from the source current head or a live snapshot.

        Parameters
        ----------
        namespace_id : str
            Source namespace id

        new_namespace_id : NamespaceId
            Durable namespace id for the fork target.

        snapshot_id : typing.Optional[PinId]
            Fork from this live snapshot instead of the current head.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Namespace
            Namespace forked

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            actor_id="YOUR_ACTOR_ID",
            subject_id="YOUR_SUBJECT_ID",
            principal_scope="YOUR_PRINCIPAL_SCOPE",
            principals="YOUR_PRINCIPALS",
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.namespaces.fork(
                namespace_id="namespace_id",
                new_namespace_id="demo",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.fork(
            namespace_id, new_namespace_id=new_namespace_id, snapshot_id=snapshot_id, request_options=request_options
        )
        return _response.data
