# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.begin_upload_request import BeginUploadRequest
from ..types.begin_upload_response import BeginUploadResponse
from ..types.complete_upload_request import CompleteUploadRequest
from ..types.sign_upload_parts_response import SignUploadPartsResponse
from ..types.upload_content_response import UploadContentResponse
from ..types.upload_part_checksum_claim import UploadPartChecksumClaim
from ..types.upload_session import UploadSession
from .raw_client import AsyncRawUploadsClient, RawUploadsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UploadsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUploadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUploadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUploadsClient
        """
        return self._raw_client

    def create_upload(
        self, namespace_id: str, *, request: BeginUploadRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> BeginUploadResponse:
        """
        Starts an upload session for content that may later be attached to a file. Service-proxied uploads send bytes through the server; direct-put uploads return object-store presigned credentials.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        request : BeginUploadRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BeginUploadResponse
            Upload session started

        Examples
        --------
        from loonfs.server import BeginUploadRequest_ServiceProxied, LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.uploads.create_upload(
            namespace_id="namespace_id",
            request=BeginUploadRequest_ServiceProxied(),
        )
        """
        _response = self._raw_client.create_upload(namespace_id, request=request, request_options=request_options)
        return _response.data

    def get_upload(
        self, namespace_id: str, upload_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UploadSession:
        """
        Returns an upload session. A completed session includes a new content token so the client can retry the commit without uploading the content again.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        upload_id : str
            Upload session id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadSession
            Upload session state

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.uploads.get_upload(
            namespace_id="namespace_id",
            upload_id="upload_id",
        )
        """
        _response = self._raw_client.get_upload(namespace_id, upload_id, request_options=request_options)
        return _response.data

    def abort_upload(
        self, namespace_id: str, upload_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UploadSession:
        """
        Ends an upload session without selecting content and deletes the object it was writing. Repeating it succeeds; a session that already completed cannot be aborted.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        upload_id : str
            Upload session id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadSession
            Upload aborted

        Examples
        --------
        from loonfs.server import LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.uploads.abort_upload(
            namespace_id="namespace_id",
            upload_id="upload_id",
        )
        """
        _response = self._raw_client.abort_upload(namespace_id, upload_id, request_options=request_options)
        return _response.data

    def complete_upload(
        self,
        namespace_id: str,
        upload_id: str,
        *,
        request: CompleteUploadRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadSession:
        """
        Completes an upload. The request mode must match the mode used to start the session. Direct uploads include a content claim; multipart also includes completed parts.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        upload_id : str
            Upload session id

        request : CompleteUploadRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadSession
            Upload completed

        Examples
        --------
        from loonfs.server import CompleteUploadRequest_ServiceProxied, LoonFS

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.uploads.complete_upload(
            namespace_id="namespace_id",
            upload_id="upload_id",
            request=CompleteUploadRequest_ServiceProxied(),
        )
        """
        _response = self._raw_client.complete_upload(
            namespace_id, upload_id, request=request, request_options=request_options
        )
        return _response.data

    def put_upload_content(
        self,
        namespace_id: str,
        upload_id: str,
        *,
        request: typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadContentResponse:
        """
        Uploads bytes into a service-proxied upload session and returns the content reference for the stored object.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        upload_id : str
            Upload session id

        request : typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadContentResponse
            Upload content accepted
        """
        _response = self._raw_client.put_upload_content(
            namespace_id, upload_id, request=request, request_options=request_options
        )
        return _response.data

    def sign_upload_parts(
        self,
        namespace_id: str,
        upload_id: str,
        *,
        parts: typing.Sequence[UploadPartChecksumClaim],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SignUploadPartsResponse:
        """
        Returns one short-lived, checksum-bound upload capability per requested part of an open direct_multipart session. Asking again for a part is how a client retries it.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        upload_id : str
            Upload session id

        parts : typing.Sequence[UploadPartChecksumClaim]
            Parts to authorize and the checksum for each part. Requesting a part
            again replaces the previous upload for that part number.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SignUploadPartsResponse
            Part capabilities issued

        Examples
        --------
        from loonfs.server import Checksum, LoonFS, UploadPartChecksumClaim

        client = LoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.uploads.sign_upload_parts(
            namespace_id="namespace_id",
            upload_id="upload_id",
            parts=[
                UploadPartChecksumClaim(
                    checksum=Checksum(
                        algorithm="sha256",
                        value="value",
                    ),
                    part_number=1,
                )
            ],
        )
        """
        _response = self._raw_client.sign_upload_parts(
            namespace_id, upload_id, parts=parts, request_options=request_options
        )
        return _response.data


class AsyncUploadsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUploadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUploadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUploadsClient
        """
        return self._raw_client

    async def create_upload(
        self, namespace_id: str, *, request: BeginUploadRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> BeginUploadResponse:
        """
        Starts an upload session for content that may later be attached to a file. Service-proxied uploads send bytes through the server; direct-put uploads return object-store presigned credentials.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        request : BeginUploadRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BeginUploadResponse
            Upload session started

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS, BeginUploadRequest_ServiceProxied

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.uploads.create_upload(
                namespace_id="namespace_id",
                request=BeginUploadRequest_ServiceProxied(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_upload(namespace_id, request=request, request_options=request_options)
        return _response.data

    async def get_upload(
        self, namespace_id: str, upload_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UploadSession:
        """
        Returns an upload session. A completed session includes a new content token so the client can retry the commit without uploading the content again.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        upload_id : str
            Upload session id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadSession
            Upload session state

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.uploads.get_upload(
                namespace_id="namespace_id",
                upload_id="upload_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_upload(namespace_id, upload_id, request_options=request_options)
        return _response.data

    async def abort_upload(
        self, namespace_id: str, upload_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UploadSession:
        """
        Ends an upload session without selecting content and deletes the object it was writing. Repeating it succeeds; a session that already completed cannot be aborted.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        upload_id : str
            Upload session id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadSession
            Upload aborted

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.uploads.abort_upload(
                namespace_id="namespace_id",
                upload_id="upload_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.abort_upload(namespace_id, upload_id, request_options=request_options)
        return _response.data

    async def complete_upload(
        self,
        namespace_id: str,
        upload_id: str,
        *,
        request: CompleteUploadRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadSession:
        """
        Completes an upload. The request mode must match the mode used to start the session. Direct uploads include a content claim; multipart also includes completed parts.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        upload_id : str
            Upload session id

        request : CompleteUploadRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadSession
            Upload completed

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS, CompleteUploadRequest_ServiceProxied

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.uploads.complete_upload(
                namespace_id="namespace_id",
                upload_id="upload_id",
                request=CompleteUploadRequest_ServiceProxied(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.complete_upload(
            namespace_id, upload_id, request=request, request_options=request_options
        )
        return _response.data

    async def put_upload_content(
        self,
        namespace_id: str,
        upload_id: str,
        *,
        request: typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadContentResponse:
        """
        Uploads bytes into a service-proxied upload session and returns the content reference for the stored object.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        upload_id : str
            Upload session id

        request : typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadContentResponse
            Upload content accepted
        """
        _response = await self._raw_client.put_upload_content(
            namespace_id, upload_id, request=request, request_options=request_options
        )
        return _response.data

    async def sign_upload_parts(
        self,
        namespace_id: str,
        upload_id: str,
        *,
        parts: typing.Sequence[UploadPartChecksumClaim],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SignUploadPartsResponse:
        """
        Returns one short-lived, checksum-bound upload capability per requested part of an open direct_multipart session. Asking again for a part is how a client retries it.

        Parameters
        ----------
        namespace_id : str
            Namespace id

        upload_id : str
            Upload session id

        parts : typing.Sequence[UploadPartChecksumClaim]
            Parts to authorize and the checksum for each part. Requesting a part
            again replaces the previous upload for that part number.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SignUploadPartsResponse
            Part capabilities issued

        Examples
        --------
        import asyncio

        from loonfs.server import AsyncLoonFS, Checksum, UploadPartChecksumClaim

        client = AsyncLoonFS(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.uploads.sign_upload_parts(
                namespace_id="namespace_id",
                upload_id="upload_id",
                parts=[
                    UploadPartChecksumClaim(
                        checksum=Checksum(
                            algorithm="sha256",
                            value="value",
                        ),
                        part_number=1,
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sign_upload_parts(
            namespace_id, upload_id, parts=parts, request_options=request_options
        )
        return _response.data
